/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.AdProvider
import com.forestvpn.api.client.models.AdReward

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param format 
 * @param provider 
 * @param externalKey 
 * @param reward 
 */


data class AdUnit (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "format")
    val format: AdUnit.Format,

    @Json(name = "provider")
    val provider: AdProvider,

    @Json(name = "external_key")
    val externalKey: kotlin.String? = null,

    @Json(name = "reward")
    val reward: AdReward? = null

) {

    /**
     * 
     *
     * Values: splash,native,rewarded,banner,interstitial,rewardedInterstitial,roll
     */
    enum class Format(val value: kotlin.String) {
        @Json(name = "splash") splash("splash"),
        @Json(name = "native") native("native"),
        @Json(name = "rewarded") rewarded("rewarded"),
        @Json(name = "banner") banner("banner"),
        @Json(name = "interstitial") interstitial("interstitial"),
        @Json(name = "rewarded_interstitial") rewardedInterstitial("rewarded_interstitial"),
        @Json(name = "roll") roll("roll");
    }
}

