/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param aggrInterval Aggregation value. It might de a hour, day, week, or month
 * @param deviceId User device name, useful for retrieve extra data through device API
 * @param deviceName User device name, useful for showing in the chart
 * @param receivedBytes Sum of the received bytes aggregated around the device and aggr_interval
 * @param transmittedBytes Sum of the transmitted bytes aggregated around the device and aggr_interval
 * @param totalBytes Sum of the received + transmitted bytes aggregated around the device and aggr_interval
 * @param usageTime Minutes of usage time aggregated around the device and aggr_interval
 */


data class AggregatedDataUsageStats (

    /* Aggregation value. It might de a hour, day, week, or month */
    @Json(name = "aggr_interval")
    val aggrInterval: kotlin.String? = null,

    /* User device name, useful for retrieve extra data through device API */
    @Json(name = "device_id")
    val deviceId: java.util.UUID? = null,

    /* User device name, useful for showing in the chart */
    @Json(name = "device_name")
    val deviceName: kotlin.String? = null,

    /* Sum of the received bytes aggregated around the device and aggr_interval */
    @Json(name = "received_bytes")
    val receivedBytes: kotlin.Int? = null,

    /* Sum of the transmitted bytes aggregated around the device and aggr_interval */
    @Json(name = "transmitted_bytes")
    val transmittedBytes: kotlin.Int? = null,

    /* Sum of the received + transmitted bytes aggregated around the device and aggr_interval */
    @Json(name = "total_bytes")
    val totalBytes: kotlin.Int? = null,

    /* Minutes of usage time aggregated around the device and aggr_interval */
    @Json(name = "usage_time")
    val usageTime: kotlin.Int? = null

)

