/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param receipt The latest Base64-encoded transaction receipt.
 * @param price 
 * @param currency 
 */


data class AppStoreReceiptVerificationRequest (

    /* The latest Base64-encoded transaction receipt. */
    @Json(name = "receipt")
    val receipt: kotlin.ByteArray,

    @Json(name = "price")
    val price: kotlin.Long? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null

)

