/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Constraint

import com.squareup.moshi.Json

/**
 * 
 *
 * @param bundleId Billing feature's slug
 * @param expiryDate Billing feature's expiry date
 * @param constraints 
 */


data class BillingFeature (

    /* Billing feature's slug */
    @Json(name = "bundle_id")
    val bundleId: kotlin.String,

    /* Billing feature's expiry date */
    @Json(name = "expiry_date")
    val expiryDate: java.time.OffsetDateTime? = null,

    @Json(name = "constraints")
    val constraints: kotlin.collections.List<Constraint>? = null

)

