/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Product

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param trialPeriod Trial period duration in ISO 8601 format.
 * @param products 
 */


data class Bundle (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    /* Trial period duration in ISO 8601 format. */
    @Json(name = "trial_period")
    val trialPeriod: kotlin.String? = null,

    @Json(name = "products")
    val products: kotlin.collections.List<Product>? = null

)

