/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Product

import com.squareup.moshi.Json

/**
 * 
 *
 * @param product 
 * @param quantity 
 */


data class CheckoutSessionProduct (

    @Json(name = "product")
    val product: Product,

    @Json(name = "quantity")
    val quantity: kotlin.Int

)

