/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.CloudPaymentsSecure3d

import com.squareup.moshi.Json

/**
 * 
 *
 * @param transactionId 
 * @param secure3d 
 */


data class CloudPaymentsAuth (

    @Json(name = "transaction_id")
    val transactionId: kotlin.Int? = null,

    @Json(name = "secure3d")
    val secure3d: CloudPaymentsSecure3d? = null

)

