/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param unit 
 * @param requestDate 
 * @param duration ISO-8601 duration format
 * @param errorCode 
 * @param errorMessage 
 */


data class CreateAdUnitRequestLogRequest (

    @Json(name = "unit")
    val unit: java.util.UUID,

    @Json(name = "request_date")
    val requestDate: java.time.OffsetDateTime,

    /* ISO-8601 duration format */
    @Json(name = "duration")
    val duration: kotlin.String,

    @Json(name = "error_code")
    val errorCode: kotlin.Int? = null,

    @Json(name = "error_message")
    val errorMessage: kotlin.String? = null

)

