/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param cryptogram 
 * @param name 
 */


data class CreateCloudPaymentsAuth (

    @Json(name = "cryptogram")
    val cryptogram: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

