/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.DeviceType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param info 
 */


data class CreateOrUpdateDeviceRequestInfo (

    @Json(name = "type")
    val type: DeviceType,

    @Json(name = "info")
    val info: kotlin.collections.Map<kotlin.String, kotlin.String>

)

