/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.ConnectionMode
import com.forestvpn.api.client.models.Location
import com.forestvpn.api.client.models.Server
import com.forestvpn.api.client.models.WireGuard

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param externalKey 
 * @param name 
 * @param ips 
 * @param dns 
 * @param torOver 
 * @param connectionMode 
 * @param wireguard 
 * @param location 
 * @param servers 
 * @param lastActiveAt 
 * @param type 
 */


data class Device (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "external_key")
    val externalKey: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "ips")
    val ips: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "dns")
    val dns: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tor_over")
    val torOver: kotlin.Boolean? = false,

    @Json(name = "connection_mode")
    val connectionMode: ConnectionMode? = null,

    @Json(name = "wireguard")
    val wireguard: WireGuard? = null,

    @Json(name = "location")
    val location: Location? = null,

    @Json(name = "servers")
    val servers: kotlin.collections.List<Server>? = null,

    @Json(name = "last_active_at")
    val lastActiveAt: java.time.OffsetDateTime? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

)

