/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: ios,ipados,watchos,macos,android,wp,other
 */

enum class DeviceType(val value: kotlin.String) {

    @Json(name = "ios")
    ios("ios"),

    @Json(name = "ipados")
    ipados("ipados"),

    @Json(name = "watchos")
    watchos("watchos"),

    @Json(name = "macos")
    macos("macos"),

    @Json(name = "android")
    android("android"),

    @Json(name = "wp")
    wp("wp"),

    @Json(name = "other")
    other("other");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DeviceType) "$data" else null

        /**
         * Returns a valid [DeviceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DeviceType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

