/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param message 
 * @param detail 
 */


data class Error (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "detail")
    val detail: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

