/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param registrationId 
 * @param active 
 * @param createdAt 
 * @param deviceId 
 */


data class FCMDevice (

    @Json(name = "registration_id")
    val registrationId: kotlin.String,

    @Json(name = "active")
    val active: kotlin.Boolean,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "device_id")
    val deviceId: kotlin.String? = null

)

