/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.User

import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param user 
 * @param shareText 
 * @param createdAt 
 */


data class FriendshipInvitation (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "user")
    val user: User,

    @Json(name = "share_text")
    val shareText: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime

)

