/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Country

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param latitude 
 * @param longitude 
 * @param country 
 * @param distance it's distance in kilometers between an user (longitude and latitude from request object) and a location object
 * @param latencyRate it's a rate from 0 to 1 which shows a connection quality. where 1 is good and 0 is bad
 * @param alternativeNames 
 */


data class Location (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "latitude")
    val latitude: kotlin.Double,

    @Json(name = "longitude")
    val longitude: kotlin.Double,

    @Json(name = "country")
    val country: Country,

    /* it's distance in kilometers between an user (longitude and latitude from request object) and a location object */
    @Json(name = "distance")
    val distance: kotlin.Double? = null,

    /* it's a rate from 0 to 1 which shows a connection quality. where 1 is good and 0 is bad */
    @Json(name = "latency_rate")
    val latencyRate: kotlin.Double? = null,

    @Json(name = "alternative_names")
    val alternativeNames: kotlin.collections.List<kotlin.String>? = null

)

