/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param slug 
 * @param title 
 * @param description 
 * @param unread 
 * @param type 
 * @param level 
 * @param recipient 
 * @param actorContentType 
 * @param actorObjectId 
 * @param verb 
 * @param createdAt 
 * @param `public` 
 * @param deleted 
 * @param `data` 
 */


data class Notification (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "slug")
    val slug: kotlin.Int,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "unread")
    val unread: kotlin.Boolean,

    @Json(name = "type")
    val type: Notification.Type,

    @Json(name = "level")
    val level: Notification.Level? = null,

    @Json(name = "recipient")
    val recipient: java.util.UUID? = null,

    @Json(name = "actor_content_type")
    val actorContentType: kotlin.Int? = null,

    @Json(name = "actor_object_id")
    val actorObjectId: java.util.UUID? = null,

    @Json(name = "verb")
    val verb: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "public")
    val `public`: kotlin.Boolean? = null,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: systemUpdate,productUpdate,nonPaper
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "system_update") systemUpdate("system_update"),
        @Json(name = "product_update") productUpdate("product_update"),
        @Json(name = "non_paper") nonPaper("non_paper");
    }
    /**
     * 
     *
     * Values: success,info,warning,error
     */
    enum class Level(val value: kotlin.String) {
        @Json(name = "success") success("success"),
        @Json(name = "info") info("info"),
        @Json(name = "warning") warning("warning"),
        @Json(name = "error") error("error");
    }
}

