/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Country

import com.squareup.moshi.Json

/**
 * 
 *
 * @param brand Card brand
 * @param last4 Last 4 digits of the card
 * @param expiresAt Last day of the expiration year and month
 * @param country 
 */


data class PaymentMethodCard (

    /* Card brand */
    @Json(name = "brand")
    val brand: kotlin.String,

    /* Last 4 digits of the card */
    @Json(name = "last4")
    val last4: kotlin.String,

    /* Last day of the expiration year and month */
    @Json(name = "expires_at")
    val expiresAt: java.time.LocalDate,

    @Json(name = "country")
    val country: Country? = null

)

