/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.PaymentMethodCard
import com.forestvpn.api.client.models.PaymentMethodType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param type 
 * @param createdAt 
 * @param card 
 */


data class PaymentMethod (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "type")
    val type: PaymentMethodType,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "card")
    val card: PaymentMethodCard? = null

)

