/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param productSku The inapp product SKU (for example, 'com.some.thing.inapp1').
 * @param purchaseToken The token provided to the user's device when the inapp product was purchased.
 */


data class PlayStorePurchaseVerificationRequest (

    /* The inapp product SKU (for example, 'com.some.thing.inapp1'). */
    @Json(name = "product_sku")
    val productSku: kotlin.String,

    /* The token provided to the user's device when the inapp product was purchased. */
    @Json(name = "purchase_token")
    val purchaseToken: kotlin.String

)

