/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param srcPort 
 * @param dstPort 
 */


data class PortForwarding (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "src_port")
    val srcPort: kotlin.Int? = null,

    @Json(name = "dst_port")
    val dstPort: kotlin.Int? = null

)

