/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Product

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param currency 
 * @param price 
 * @param product 
 */


data class Price (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "price")
    val price: kotlin.Double,

    @Json(name = "product")
    val product: Product? = null

)

