/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.Bundle
import com.forestvpn.api.client.models.Discount
import com.forestvpn.api.client.models.Recurring

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param bundle 
 * @param recurring 
 * @param discount 
 * @param isMostPopular 
 */


data class ProductWithoutPrice (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "bundle")
    val bundle: Bundle? = null,

    @Json(name = "recurring")
    val recurring: Recurring? = null,

    @Json(name = "discount")
    val discount: Discount? = null,

    @Json(name = "is_most_popular")
    val isMostPopular: kotlin.Boolean? = null

)

