/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param sessionId 
 * @param successUrl 
 * @param cancelUrl 
 */


data class StripeCheckoutSession (

    @Json(name = "session_id")
    val sessionId: kotlin.String,

    @Json(name = "success_url")
    val successUrl: kotlin.String,

    @Json(name = "cancel_url")
    val cancelUrl: kotlin.String

)

