/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.SubscriptionItem
import com.forestvpn.api.client.models.SubscriptionSource
import com.forestvpn.api.client.models.SubscriptionStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param startDate 
 * @param currentPeriodStart Start of the current period that the subscription has been invoiced for.
 * @param currentPeriodEnd End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created.
 * @param status 
 * @param promotionalCode 
 * @param source 
 * @param endedAt If the subscription has ended, the date the subscription ended.
 * @param trialStart If the subscription has a trial, the beginning of that trial.
 * @param trialEnd If the subscription has a trial, the end of that trial.
 * @param cancelAt A date in the future at which the subscription will automatically get canceled.
 * @param canceledAt If the subscription has been canceled, the date of that cancellation.
 * @param description The subscription’s description, meant to be displayable to the customer.
 * @param items 
 */


data class Subscription (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "start_date")
    val startDate: java.time.OffsetDateTime,

    /* Start of the current period that the subscription has been invoiced for. */
    @Json(name = "current_period_start")
    val currentPeriodStart: java.time.OffsetDateTime,

    /* End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created. */
    @Json(name = "current_period_end")
    val currentPeriodEnd: java.time.OffsetDateTime,

    @Json(name = "status")
    val status: SubscriptionStatus,

    @Json(name = "promotional_code")
    val promotionalCode: kotlin.String? = null,

    @Json(name = "source")
    val source: SubscriptionSource? = null,

    /* If the subscription has ended, the date the subscription ended. */
    @Json(name = "ended_at")
    val endedAt: java.time.OffsetDateTime? = null,

    /* If the subscription has a trial, the beginning of that trial. */
    @Json(name = "trial_start")
    val trialStart: java.time.OffsetDateTime? = null,

    /* If the subscription has a trial, the end of that trial. */
    @Json(name = "trial_end")
    val trialEnd: java.time.OffsetDateTime? = null,

    /* A date in the future at which the subscription will automatically get canceled. */
    @Json(name = "cancel_at")
    val cancelAt: java.time.OffsetDateTime? = null,

    /* If the subscription has been canceled, the date of that cancellation. */
    @Json(name = "canceled_at")
    val canceledAt: java.time.OffsetDateTime? = null,

    /* The subscription’s description, meant to be displayable to the customer. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<SubscriptionItem>? = null

)

