/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param access 
 * @param refresh 
 * @param loginUrl 
 */


data class TokenObtain (

    @Json(name = "access")
    val access: kotlin.String,

    @Json(name = "refresh")
    val refresh: kotlin.String,

    @Json(name = "login_url")
    val loginUrl: kotlin.String

)

