/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appsflyerId 
 * @param gaid 
 * @param idfa 
 * @param idfv 
 * @param oaid 
 * @param amazonAid 
 * @param imei 
 * @param ref 
 */


data class UpdateUserDeviceRequest (

    @Json(name = "appsflyer_id")
    val appsflyerId: kotlin.String? = null,

    @Json(name = "gaid")
    val gaid: kotlin.String? = null,

    @Json(name = "idfa")
    val idfa: kotlin.String? = null,

    @Json(name = "idfv")
    val idfv: kotlin.String? = null,

    @Json(name = "oaid")
    val oaid: kotlin.String? = null,

    @Json(name = "amazon_aid")
    val amazonAid: kotlin.String? = null,

    @Json(name = "imei")
    val imei: kotlin.String? = null,

    @Json(name = "ref")
    val ref: kotlin.String? = null

)

