/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.WireGuardPeerDevice
import com.forestvpn.api.client.models.WireGuardPeerUser

import com.squareup.moshi.Json

/**
 * 
 *
 * @param pubKey 
 * @param user 
 * @param device 
 */


data class WireGuardPeerInfo (

    @Json(name = "pub_key")
    val pubKey: kotlin.String? = null,

    @Json(name = "user")
    val user: WireGuardPeerUser? = null,

    @Json(name = "device")
    val device: WireGuardPeerDevice? = null

)

