/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models

import com.forestvpn.api.client.models.WireGuardPeer

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param privKey 
 * @param pubKey 
 * @param peers 
 */


data class WireGuard (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "priv_key")
    val privKey: kotlin.String,

    @Json(name = "pub_key")
    val pubKey: kotlin.String,

    @Json(name = "peers")
    val peers: kotlin.collections.List<WireGuardPeer>

)

