/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.forestvpn.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param pubKey 
 * @param psKey 
 * @param endpoint 
 * @param allowedIps 
 */


data class WireGuardPeer (

    @Json(name = "pub_key")
    val pubKey: kotlin.String,

    @Json(name = "ps_key")
    val psKey: kotlin.String? = null,

    @Json(name = "endpoint")
    val endpoint: kotlin.String? = null,

    @Json(name = "allowed_ips")
    val allowedIps: kotlin.collections.List<kotlin.String>? = null

)

